language: python
dist: xenial
python:
  - "3.7"
install:
  - pip install .[test]
before_script:
    - sudo redis-server /etc/redis/redis.conf --port 26379
# command to run tests
script:
  - coverage run -m pytest
after_success:
  - codecov
  - coveralls